name: Process XML

on:
  pull_request:
    paths:
      - 'template.xml'

jobs:
  process-xml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Extract Title from XML
        id: extract-title
        run: echo "::set-output name=title::$(xmllint --xpath 'string(/song/properties/titles/title)' template.xml)"

      - name: Create XML File in res Folder
        run: echo "${{ steps.extract-title.outputs.title }}" > "res/songs${{ steps.extract-title.outputs.title }}.xml"
