name: Parse XML and Copy to Res Folder

on:
  push:
    paths:
      - '**/template.xml'
  pull_request:
    paths:
      - '**/template.xml'

jobs:
  copy-xml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  

      - name: Extract title from XML
        run: |
          python script.py
          cp template.xml res/

  execute-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python
        run: |
          sudo apt-get update
          sudo apt-get install python3.8

      - name: Install dependencies
        run: |
          python3.8 -m pip install --upgrade pip
          pip3 install -r requirements.txt  

      - name: Execute Python script
        run: python3.8 script.py
