jobs:
  copy-xml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Extract title from XML
        run: |
          import xml.etree.ElementTree as ET

          # Parse the XML file
          tree = ET.parse('template.xml')

          # Find the title element
          title = tree.find('.//title').text

          # Use the title to create a new file name
          new_file_name = title + '.xml'
      - name: Copy XML to Res Folder
        run: |
          cp template.xml res/
          cp $new_file_name res/
      - name: Commit changes
        run: |
          git config --global user.email "lavintom007@gmail.com"
          git config --global user.name "Lavin-tom"
          git commit -am "Add template.xml to res folder"
          git push
